#!/usr/bin/python3
import os
import sys

# Get the PYCODE environment variable
pycode = os.getenv('PYCODE')

# Check if the PYCODE environment variable is set
if pycode is None:
    print("Error: PYCODE environment variable is not set.")
    sys.exit(1)

# Run the Python code
exec(pycode)

